properties:
  configuration:
    runtime:
      name: node
      version: "18"
  template:
    containers:
      - name: robot-fleet-api
        image: robotfleetregistry.azurecr.io/robot-fleet-minimal:latest
        env:
          - name: NODE_ENV
            value: "production"
          - name: PORT
            value: "3001"
          - name: JWT_SECRET
            value: "robot-fleet-jwt-secret-2024"
          - name: IOT_HUB_CONNECTION_STRING
            value: "HostName=robot-fleet-hub.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=B16xWehoM1PG9y5cq1+a5FYdQusJScCJdAIoTJZUPww="
          - name: STORAGE_CONNECTION_STRING
            value: "DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=robotfleetstorage2024;AccountKey=6HVAj6fe/9g+A6lkarTcS5lv/XrkJcEN+Xy/6JhvHoQlizw9dQICanZWtLF5C5W3d7k2Ai5gv8zi+AStFe38Vg=="
          - name: COSMOS_DB_ENDPOINT
            value: "https://robot-fleet-cosmos.documents.azure.com:443/"
          - name: COSMOS_DB_KEY
            value: "TIzreRbB8MkTguGtX8r0ZFhMfOc33QpiUT1aWaZA5bTwMgtjGgyZYwdFef8VOCvNGdpT1LKtVzb5ACDbuivWMw=="
          - name: DIGITAL_TWINS_ENDPOINT
            value: "https://robot-fleet-digital-twins.api.eus.digitaltwins.azure.net"
        resources:
          cpu: 0.5
          memory: 1Gi
