"""
Optional Azure Digital Twins projection adapter.

This module keeps Azure-specific dependencies out of the core mapping logic.
It can be used to load DTDL models and apply ADT-style patch documents
generated by TwinMapper when an Azure Digital Twins instance is available.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import hashlib
import json
from pathlib import Path
import re
from typing import Any, Protocol

from .twin_mapper import TwinPatchDocument


class TwinProjectionAdapter(Protocol):
    """Interface for any target that can consume twin patch documents."""

    def apply_patch(self, document: TwinPatchDocument) -> dict[str, Any]:
        ...


@dataclass
class RecordedTwinOperation:
    """Serializable record of one projected twin operation."""

    twin_id: str
    model_id: str
    patch: list[dict[str, Any]]
    relationships: list[dict[str, Any]]


@dataclass
class InMemoryTwinProjectionAdapter:
    """Collect projected operations for tests, dry runs, and previews."""

    operations: list[RecordedTwinOperation] = field(default_factory=list)
    provisioned_twins: list[dict[str, Any]] = field(default_factory=list)
    provisioned_relationships: list[dict[str, Any]] = field(default_factory=list)

    def apply_patch(self, document: TwinPatchDocument) -> dict[str, Any]:
        operation = RecordedTwinOperation(
            twin_id=document.twin_id,
            model_id=document.model_id,
            patch=document.patch,
            relationships=document.relationships,
        )
        self.operations.append(operation)
        return {
            "twin_id": document.twin_id,
            "model_id": document.model_id,
            "patch_count": len(document.patch),
            "relationship_count": len(document.relationships),
        }

    def upsert_twin(self, twin_id: str, model_id: str, properties: dict[str, Any]) -> dict[str, Any]:
        record = {"$dtId": twin_id, "$metadata": {"$model": model_id}, **properties}
        self.provisioned_twins.append(record)
        return record

    def upsert_relationship(self, source_id: str, relationship_name: str, target_id: str) -> dict[str, str]:
        record = {
            "$relationshipId": build_relationship_id(source_id, relationship_name, target_id),
            "$sourceId": source_id,
            "$relationshipName": relationship_name,
            "$targetId": target_id,
        }
        self.provisioned_relationships.append(record)
        return record


class AzureDigitalTwinsAdapter:
    """Apply TwinPatchDocument instances to a real Azure Digital Twins instance."""

    def __init__(self, client: Any):
        self._client = client

    @classmethod
    def from_default_credential(cls, adt_url: str) -> "AzureDigitalTwinsAdapter":
        """Construct the adapter using DefaultAzureCredential."""
        try:
            from azure.digitaltwins.core import DigitalTwinsClient
            from azure.identity import DefaultAzureCredential
        except ImportError as exc:
            raise RuntimeError(
                "azure-digitaltwins-core and azure-identity are required to use AzureDigitalTwinsAdapter."
            ) from exc

        credential = DefaultAzureCredential()
        client = DigitalTwinsClient(adt_url, credential)
        return cls(client)

    def create_models(self, models: list[dict[str, Any]]) -> Any:
        """Create one or more DTDL models in Azure Digital Twins."""
        return self._client.create_models(models)

    def upsert_twin(self, twin_id: str, model_id: str, properties: dict[str, Any]) -> Any:
        payload = dict(properties)
        payload["$metadata"] = {"$model": model_id}
        return self._client.upsert_digital_twin(twin_id, payload)

    def upsert_relationship(self, source_id: str, relationship_name: str, target_id: str) -> Any:
        relationship_id = build_relationship_id(source_id, relationship_name, target_id)
        body = {
            "$relationshipId": relationship_id,
            "$sourceId": source_id,
            "$relationshipName": relationship_name,
            "$targetId": target_id,
        }
        return self._client.upsert_relationship(source_id, relationship_id, body)

    def apply_patch(self, document: TwinPatchDocument) -> dict[str, Any]:
        """
        Upsert the twin shell, apply the JSON patch, and ensure relationships exist.

        The model shell is written first so the patch can be replayed safely.
        """
        base_twin = {"$metadata": {"$model": document.model_id}}
        self._client.upsert_digital_twin(document.twin_id, base_twin)

        if document.patch:
            self._client.update_digital_twin(document.twin_id, document.patch)

        relationships = []
        for relationship in document.relationships:
            relationship_id = build_relationship_id(
                document.twin_id,
                relationship["relationshipName"],
                relationship["targetId"],
            )
            body = {
                "$relationshipId": relationship_id,
                "$sourceId": document.twin_id,
                "$relationshipName": relationship["relationshipName"],
                "$targetId": relationship["targetId"],
            }
            self._client.upsert_relationship(document.twin_id, relationship_id, body)
            relationships.append(body)

        return {
            "twin_id": document.twin_id,
            "model_id": document.model_id,
            "patch_count": len(document.patch),
            "relationship_count": len(relationships),
        }


def build_relationship_id(source_id: str, relationship_name: str, target_id: str) -> str:
    """Build a deterministic ADT relationship identifier."""
    digest = hashlib.sha1(f"{source_id}|{relationship_name}|{target_id}".encode("utf-8")).hexdigest()[:12]
    slug = _slugify(f"{relationship_name}-{digest}")
    return f"rel--{slug}"


def load_dtdl_models(path: str | Path) -> list[dict[str, Any]]:
    """Load one or more DTDL models from a JSON file."""
    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    if isinstance(payload, list):
        return payload
    return [payload]


def _slugify(value: str) -> str:
    return re.sub(r"[^a-zA-Z0-9-]+", "-", value).strip("-").lower()
