"""
Canonical fleet event contracts for local-first development.

These dataclasses define the stable payloads shared between the edge bridge,
projection services, and future cloud adapters.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime, timezone
import json
from typing import Any
from uuid import uuid4


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


@dataclass(frozen=True)
class EventMetadata:
    """Envelope metadata common to all canonical fleet events."""

    event_id: str
    event_type: str
    schema_version: str
    occurred_at: str
    source: str
    robot_id: str
    fleet_id: str
    site_id: str
    tenant_id: str
    sequence: int = 0
    correlation_id: str | None = None


@dataclass(frozen=True)
class RobotTelemetryPayload:
    """Operational robot telemetry used for projections and analytics."""

    status: str
    battery_pct: float | None
    pose: dict[str, float]
    robot_type: str
    robot_category: str
    vendor: str
    velocity: list[float] | None = None


@dataclass(frozen=True)
class RobotHealthPayload:
    """Health-oriented state that remains useful even in stub simulation."""

    connectivity: str
    battery_pct: float | None
    health_status: str
    active_alerts: list[str]


@dataclass(frozen=True)
class RobotTaskStatusPayload:
    """Task status changes reported by the controller or edge bridge."""

    task_id: str
    task_status: str
    summary: str
    details: dict[str, Any]


@dataclass(frozen=True)
class RobotIntentPayload:
    """High-level robot intent derived from control state."""

    intent_type: str
    target: str
    confidence: float
    notes: str = ""


@dataclass(frozen=True)
class RobotAlertPayload:
    """Alert payload for fault and exception routing."""

    severity: str
    code: str
    message: str
    details: dict[str, Any]


@dataclass(frozen=True)
class FleetCommandPayload:
    """Cloud-to-edge command contract to keep control traffic aligned early."""

    command_type: str
    issued_by: str
    parameters: dict[str, Any]


@dataclass(frozen=True)
class TwinProjectionPayload:
    """Projection record describing a state update applied to a twin."""

    entity_type: str
    entity_id: str
    projection_type: str
    fields: dict[str, Any]


@dataclass(frozen=True)
class MissionIntentPayload:
    """Structured mission request emitted after intent parsing."""

    mission_id: str
    mission_type: str
    objective: str
    requested_by: str
    source_zone: str | None
    destination_zone: str | None
    required_capabilities: list[str]
    constraints: dict[str, Any]


@dataclass(frozen=True)
class ResourceAssessmentPayload:
    """Snapshot summary describing allocatable fleet resources."""

    snapshot_id: str
    total_robots: int
    available_robot_ids: list[str]
    unavailable_robot_ids: list[str]
    summary: dict[str, Any]


@dataclass(frozen=True)
class MissionPlanPayload:
    """Plan summary generated by the mission planner."""

    mission_id: str
    task_ids: list[str]
    assignment_ids: list[str]
    unassigned_task_ids: list[str]
    status: str
    explanation: str


@dataclass(frozen=True)
class TaskAssignmentPayload:
    """Assignment decision for a planned task."""

    assignment_id: str
    mission_id: str
    task_id: str
    robot_id: str
    status: str
    score: float | None
    rationale: str


@dataclass(frozen=True)
class MissionExecutionPayload:
    """Execution state for a mission after dispatch or refresh."""

    mission_id: str
    status: str
    active_task_id: str | None
    completed_task_ids: list[str]
    blocked_task_ids: list[str]
    notes: str


@dataclass(frozen=True)
class ExplanationPayload:
    """Operator-facing explanation generated by the brain."""

    explanation_id: str
    mission_id: str
    title: str
    summary: str
    details: dict[str, Any]


@dataclass(frozen=True)
class CanonicalEvent:
    """Envelope plus typed payload."""

    metadata: EventMetadata
    payload: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        return {
            "metadata": asdict(self.metadata),
            "payload": self.payload,
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), separators=(",", ":"), sort_keys=True)


def make_metadata(
    *,
    event_type: str,
    source: str,
    robot_id: str,
    fleet_id: str,
    site_id: str,
    tenant_id: str,
    schema_version: str,
    sequence: int = 0,
    correlation_id: str | None = None,
) -> EventMetadata:
    """Create standard metadata for a canonical event."""
    return EventMetadata(
        event_id=str(uuid4()),
        event_type=event_type,
        schema_version=schema_version,
        occurred_at=_utc_now_iso(),
        source=source,
        robot_id=robot_id,
        fleet_id=fleet_id,
        site_id=site_id,
        tenant_id=tenant_id,
        sequence=sequence,
        correlation_id=correlation_id,
    )


def event_from_payload(metadata: EventMetadata, payload: Any) -> CanonicalEvent:
    """Wrap a dataclass payload into a canonical event."""
    return CanonicalEvent(metadata=metadata, payload=asdict(payload))


def event_from_dict(data: dict[str, Any]) -> CanonicalEvent:
    """Rehydrate a canonical event from a serialized dict."""
    metadata = EventMetadata(**data["metadata"])
    return CanonicalEvent(metadata=metadata, payload=data["payload"])
